[squash merge] Feat/monitor blocking syscalls (#6)
* feat(perf): trace blocking syscalls

* chore(gcc): load libasan properly

* chore(trace): ignore select syscall block

* chore(docs): add comments on github actions

* chore(tracing): dump stack trace on bpftrace

* chore(ci): disable bpftrace check on ci

* chore(style): clean up comp variables

diff --git a/.github/workflows/pr-perf-cb.yaml b/.github/workflows/pr-perf-cb.yaml
--- a/.github/workflows/pr-perf-cb.yaml
+++ b/.github/workflows/pr-perf-cb.yaml
@@ -17,6 +17,8 @@ on:
     branches:
       - main
 
+permissions: write-all
+
 jobs:
   benchmark:
     name: Performance regression check
@@ -25,7 +27,9 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Run benchmark
-        run: docker compose up --build --abort-on-container-exit benchmark
+        run: |
+          echo "DEBUG=0" > .env
+          docker compose up --build --abort-on-container-exit benchmark
       
       - name: Format benchmark output
         run: |
@@ -64,9 +68,33 @@ jobs:
           # Workflow will fail when an alert happens
           fail-on-alert: true
           # GitHub API token to make a commit comment
-          github-token: ${{ secrets.ACCESS_TOKEN }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
           alert-threshold: '200%'
           auto-push: false
           skip-fetch-gh-pages: true
           comment-always: true
           summary-always: true
+
+  bpftrace:
+    if: false # disable due to gha flakiness
+    name: bpftrace syscall check
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        
+      - name: Build bpftrace container
+        run: docker compose build trace
+
+      - name: Run trace
+        run: |
+          set +e
+          docker compose down || true
+          timeout 10s docker compose up --abort-on-container-exit trace
+          exit_code=$?
+          if [ $exit_code -eq 0 ] || [ $exit_code -eq 124 ]; then
+            echo "Benchmark finished successfully or timed out (which is expected)."
+            exit 0
+          else
+            echo "Benchmark failed with exit code $exit_code"
+            exit $exit_code
+          fi
